@Api_HostAddress = https://apiapp-pz4csvrteejy6.azurewebsites.net

POST {{Api_HostAddress}}/api/urls
Accept: application/json
Content-Type: application/json

{
  "LongUrl": "https://dailymail.com"
}

###
