name: Web APP

on:
    push:
      branches: [ "main" ]
      paths:
        - WebApp/**
    pull_request:
      branches: [ "main" ]
      paths:
        - WebApp/**
    workflow_dispatch: # manual trigger

env:
  APP_LOCATION: "./WebApp/urlshortener-web-app/"

jobs:
 build_and_deploy_dev:
  runs-on: ubuntu-latest
  name: 'Build and Deploy to Development'
  environment: Development
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        output_location: "build" 
      env: 
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
        REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}


 build_and_deploy_stg:
   runs-on: ubuntu-latest
   name: 'Build and Deploy to Staging'
   environment: Staging
   needs: build_and_deploy_dev
   steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        output_location: "build" 
      env: 
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
        REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}

          
 build_and_deploy_prd:
    runs-on: ubuntu-latest
    name: 'Build and Deploy to Production'
    environment: Production
    needs: build_and_deploy_stg
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: "build" 
        env: 
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}
